model: "gpt-4o-mini"

temperature: 0.2

max_tokens: 1200

categories:
  - correctness      # Bugs, logic errors, broken code
  - performance      # Inefficient or slow patterns
  - security         # Leaks, injection risks, unsafe code
  - readability      # Clean code, maintainability, comments
  - best_practices   # Style, conventions, design issues
  - tests            # Unit/integration test coverage

severity_threshold: "medium"

comment_mode: "summary"

max_changed_files: 50
max_diff_bytes: 50000

prompt_overrides:
  summary_prefix: "**pullrequest-gpt review**"