name: PR Review (pullrequest-gpt)

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: prgpt-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Detect config file
        id: detect
        run: |
          if [ -f "config.prgpt.yml" ]; then
            echo "has_config=true" >> $GITHUB_OUTPUT
            echo "config_arg=--config config.prgpt.yml" >> $GITHUB_OUTPUT
          else
            echo "has_config=false" >> $GITHUB_OUTPUT
            echo "config_arg=" >> $GITHUB_OUTPUT
          fi

      - name: Run pullrequest-gpt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -e
          python backend/main.py \
            --repo "${{ github.repository }}" \
            --pr "${{ github.event.pull_request.number }}" \
            --ref "${{ github.sha }}" \
            ${{ steps.detect.outputs.config_arg }} \
            --out "prgpt_report.md"

      - name: Prepare report body
        id: read_report
        run: |
          body="$(cat prgpt_report.md | sed 's/%/%25/g; s/\n/%0A/g; s/\r/%0D/g')"
          echo "body=$body" >> $GITHUB_OUTPUT

      - name: Comment results on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🤖 **pullrequest-gpt** analysis
            ---
            ${{ steps.read_report.outputs.body }}

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: prgpt-report
          path: prgpt_report.md
